id: I1D008484
legacy_id: P009621
ocr_import_info:
  bdrc_scan_id: W3PD435
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T23:03:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:03:03.195491+00:00'
last_modified: 2022-09-04 02:03:45.353914
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3PD435
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3PD435
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡོན་ཏན་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འགྲེལ་པ་ཉི་ཟླའི་སྒྲོན་མེ་ཐུབ་དགའ་ཡིད་བཞིན་ནོར་བུའི་ཕྱག་མཆན་ཅན།
  author: བ་ཐུར་མཁན་པོ་ཐུབ་བསྟན་ཆོས་འཕེལ།
statistics:
  ocr_word_mean_confidence_index: 0.7102020933564775
  ocr_word_median_confidence_index: 0.7599999904632568
quality: null
bases:
  I3PD867:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3PD867
      total_pages: 774
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3PD867.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7161074878590035
    legacy_id: v001
  I3PD868:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3PD868
      total_pages: 606
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3PD868.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.7035082189681765
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
