id: P009621
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:41:16.913591
source_metadata:
  id: bdr:W3PD435
  title: ཡོན་ཏན་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འགྲེལ་པ་ཉི་ཟླའི་སྒྲོན་མེ་ཐུབ་དགའ་ཡིད་བཞིན་ནོར་བུའི་ཕྱག་མཆན་ཅན།
  author: ''
  volumes:
    0193d22c48d34f74b867f3b8fed0b157:
      image_group_id: I3PD867
      title: ''
      volume_number: 1
      total_pages: 774
      base_file: v001.txt
    abb66e7f06834537919dc4b6ff72a21b:
      image_group_id: I3PD868
      title: ''
      volume_number: 2
      total_pages: 606
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
