id: opecha:P009621
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD435
  title: ཡོན་ཏན་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འགྲེལ་པ་ཉི་ཟླའི་སྒྲོན་མེ་ཐུབ་དགའ་ཡིད་བཞིན་ནོར་བུའི་ཕྱག་མཆན་ཅན།
  volume: ''
  author: ''
